name: Publish Tech Blog
on:
  push:
    branches: [main]
    paths: ['Articles/**.md']

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # 1) Articles → _dist にコピー＆変換
      - name: Build Qiita & Zenn trees
        run: |
          mkdir -p _dist/qiita _dist/zenn/articles _dist/zenn/images
          find Articles -name '*.md' -type f | while read f; do
            rel="${f#Articles/}"               # 01-section/01-01/foo.md
            dir=$(dirname "$rel")
            base=$(basename "$f")
            slug=$(echo "$base" | tr 'A-Z_' 'a-z-' | sed 's/\.md$//')

            # ---- Qiita ----
            outq="_dist/qiita/$dir/$base"
            mkdir -p "$(dirname "$outq")"
            sed -E "s#\\((images/[^)]+)\\)#(https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_SHA}/Articles/$dir/\\1)#g" "$f" > "$outq"

            # ---- Zenn ----  (articles/slug.md + 画像はリポジトリ直下 images/)
            outz="_dist/zenn/articles/${slug}.md"
            mkdir -p "$(dirname "$outz")"
            cp "$f" "$outz"

            if [ -d "$(dirname "$f")/images" ]; then
              cp -r "$(dirname "$f")/images/"* "_dist/zenn/images/" || true
            fi
          done

      # 2) Qiita へ投稿
      - name: Publish to Qiita
        uses: noraworld/github-to-qiita@v1
        with:
          dir: _dist/qiita
          qiita_access_token: ${{ env.QIITA_TOKEN }}

      # 3) Zenn 用ブランチへ force-push
      - name: Push to Zenn branch
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan zenn-sync
          mv _dist/zenn/* .
          git add articles images
          git commit -m "sync: zenn $(date +%F)" || true
          git push -f origin zenn-sync:zenn-main   # Zenn が監視するブランチ
